### PR TITLE
Create main.json

### PR DESCRIPTION
**Pull request by DDinghoya**

### CODE REVIEW

**Comment by XITRIX** [comment]
Thanks for your translation, but I think you used wrong language code, it should be "ko" instead of "kr-KO", could you fix it?

**Comment by DDinghoya** [comment]
> Thanks for your translation, but I think you used wrong language code, it should be "ko" instead of "kr-KO", could you fix it?

Yes, I'll do it.

By the way, I'm also confused. :)

Because some developers use kr-KO and others use ko.

**Comment by XITRIX** [comment]
image
Here is the table of supported by HOS localizations, it uses "ko" for Korean

**Comment by DDinghoya** [comment]
Thank you for your strong support!

**Pull request closed without merging**
